export {default as fittings_1} from "./fiitings (1).jpg"
export {default as fittings_2} from "./fiitings (2).jpg"
export {default as fittings_3} from "./fiitings (3).jpg"
export {default as fittings_4} from "./fiitings (4).jpg"
export {default as fittings_5} from "./fiitings (5).jpg"
export {default as fittings_6} from "./fiitings (6).jpg"
export {default as fittings_7} from "./fiitings (7).jpg"