import NavbarCompt from '@/components/layouts/navbar/page'
import Footer from '@/components/layouts/footer/page'
import './globals.css'
import type { Metadata } from 'next'
import { Lato } from "next/font/google";
import Cta from '@/components/UI/Cta';
import Providers from '@/utils/providers';


const lato = Lato({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  style: ['normal', 'italic'],
})

export const metadata: Metadata = {
  title: 'AGP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Providers>
          <NavbarCompt />
          {children}
          <Cta />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
